micronaut:
  application:
    name: book-reservation
  server:
    port: 8080
    context-path: /api
  http:
    client:
      read-timeout: 20
  executors:
      virtual: true
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml

